@startwbs
'https://plantuml.com/wbs-diagram

* Архитектура
** Здание
*** Назначение
*** Фундамент
**** Бетон
**** Кирпичи
**** -
**** -
*** Несущие стены
**** -
**** -
**** -
**** -
**** -
**** -
**** -
**** -
**** -
**** -
**** -
**** -
**** -
**** -
*** Этажи
**** Технический
**** Жилой
**** Служебный
**** -
**** -
*** Комната
*** Отделка и мебелировка

** Человек
*** Образ
*** Фундамент
**** Характер и темперамент
**** Здоровье телесное и духовное
***** Природный дар
***** Производная от образа жизни
*** Несущие стены
**** Сила воли и сила духа
**** Физическое развитие
***** Сила
***** Ловкость
***** Выносливость
***** Двигательные навыки
**** Ум
***** Память
***** Мышление
****** восприятие окружающего мира
****** понимание — способность понимать
****** обобщение — нахождение общего
****** познание — способность учиться
***** Принятие решений
*** Сферы деятельности (семья, учеба, работа, спорт, …)
**** Конкретная сфера деятельности
***** Знания — отражают действительность в голове человека
***** Умения — способность выполнять действия, которые знаешь
***** Навыки — выполняешь действия, не думая как
***** Привычка — делание на «автомате»
*** Направление в конкретной сфере деятельности (математика, медицина)
*** Культура и воспитание
@endwbs