@startuml
skinparam groupInheritance 2
hide empty members
scale 3508*2480

header
<color:red>**Актуальные идеологии**</color>
end header

legend
Создано на основе лекций:
 * Игоря Сергеевича ШИШКИНА
 * Александра Гельевича ДУГИНА
 * Константина Валентиновича СИВКОВА
 * Андрея Ильича ФУРСОВА
 * Игоря СТЕЧКИНА (ONYQ)
Использованы информационные ресурсы:
 * [[https://dentv.ru/about/ Аналитический интернет-канал «День ТВ»]]
 * [[https://nday.club Телеканал «Новый День»]]
end legend

footer  <img:https://i.creativecommons.org/l/by-sa/4.0/88x31.png>

enum Фобии {
  Русофобия
  Славянофобия
  Антисемитизм
}

abstract Идеология{
..Определяет..
Цель социума
Средства достижения цели
}

class Колониализм{
}

class "Общество потребления"{
}

abstract Либерализм{
Изменения: Эволюционные
Личное/Общее: Абсолютно личное
Общество/Государство: Общество
Экономика: Свободный рынок
Гос власть: Разделение властей
Смена гос власти: Продажные выборы
Идеология: Тоталитарная, управляемая\n\t верхушкой элиты
Закон служит: Денежным мешкам
Выгодоприобретатель: Транснациональный капитал
}

abstract Марксизм{
Изменения: Революционные
Личное/Общее: Абсолютно общее
Общество/Государство: Государство
Экономика:Страна-корпорация
Гос власть: Единство ветвей власти
Смена гос власти: Формальные выборы
Идеология: Идеократия
Закон служит: Соц. справедливости
Выгодоприобретатель: Большинство

}

abstract Консерватизм{
Изменения: Тормозим
Личное/Общее: Общее
Общество/Государство: Государство
Экономика: Гос. регулирование
Гос власть: Разделение властей с ведущей
Смена гос власти: Формальные выборы
Идеология: Терпимость
Закон служит: Элите
Выгодоприобретатель: Элита
}

abstract Анархизм{
Личное/Общее: Абсолютно личное
Экономика: Свободный рынок
Гос власть: Нет
Смена гос власти: -
Идеология: Плюрализм
Закон служит: Малым общинам
Выгодоприобретатель: Бандит
}

abstract "Компрадорский либерализм"{
Личное/Общее: Абсолютно личное
Экономика:Свободный рынок
Гос власть: Разделение властей
Смена гос власти: Продажные выборы
Идеология: Тоталитарная, управляемая\n\t верхушкой элиты
Закон служит: Денежным мешкам
Выгодоприобретатель: Метрополия
}

abstract "Авторитарный режим"{
Личное/Общее: Личное для элиты, общее для народа
Экономика: Гос. регулирование
Гос власть: Единство ветвей с приоритетом исполн.
Смена гос власти: Узурпация с формальными выборами
Идеология: Идеократия
Закон служит: Клан у власти
Выгодоприобретатель: Клан у власти
}

abstract Фашизм{
Личное/Общее: Абсолютно общее
Экономика: Ведущая роль гос.
Гос власть: Единство ветвей с приоритетом исполн.
Смена гос власти: Узурпация
Идеология: Идеократия
Закон служит: Политической целесообразности
Выгодоприобретатель: Национальный капитал
}

abstract Нацизм {
Личное/Общее: Абсолютно общее для нации
Экономика: Ведущая роль гос.
Гос власть: Единство ветвей с приоритетом исполн.
Смена гос власти: Узурпация
Идеология: Идеократия
Закон служит: Политической целесообразности
Выгодоприобретатель: Национальный капитал
 Фобии[] 
}

annotation  Русофобия #pink{
..Признаки:..
Взваливание на русских коллективной вины
Дискриминация по принадлежности к русскому народу
Противопоставление русских другим народам России,\n\t даже в позитивном ключе
Ненависть к русским, к русской культуре
Отношение к русским как к недочеловекам
Принадлежность к "малому народу" (по Шафаревичу)

}

annotation "Пятая колонна" #pink{
..Классификация..
1. Предатели купленные: единицы
2. Предатели "наивные" (наивно думают, что\n\t Запад - это почти рай): до 10%
3. Обманутый народ (когда поверит,\n\t что «заграница нам поможет»): до 70%
..Когда активно действовали..
Российская империя: 1917 год
СССР: 1980-1991 гг.
Украина: с 2013 года
Россия: 1991 - 24.02.2022
Россия после 24.02.2022 - пока не известно
..Ты узнаешь их по словам про..
Европу от Лиссабона до Владивостока
Деградировавшую элиту Запада
Необходимость прекратить войну
Нужно просить Запад научить нас\n\t как жить (отношения вассал-сюзерен)
Привлечение иностранных инвесторов
Ненужно производить то, что\n\t "плохо получается" - всё купим
.. Они продвигают..
Людей, искренни восхищающихся Западом
Кредитную зависимость от метрополии
Западные стандарты 
Общество потребления
Дибилизацию образования
.. Текущий статус пятой колонны ..
Предатели купленные: есть,\n\t у них сейчас отбирают имущество
Предатели "наивные": внедрены везде
Обманутый народ: пока нет
}

Идеология    <|--   Марксизм
Идеология    <|--   Либерализм
Идеология    <|--   Консерватизм
Идеология    <|.right.  "Общество потребления" 
Идеология    <|.left.  "Колониализм"

Либерализм   <|--   Анархизм
Либерализм   <|--   "Компрадорский либерализм"

Консерватизм <|--   "Авторитарный режим"
Консерватизм <|--   Фашизм
Консерватизм <|--   Нацизм

Нацизм::Фобии *-down-"1..*" Фобии
Фобии::Русофобия *-left- Русофобия

"Компрадорский либерализм" *-- "Пятая колонна"


@enduml