@startuml
skinparam groupInheritance 2
hide empty members
scale 3508*2480

header
<color:red>**Актуальные идеологии**</color>
end header

legend
Создано на основе лекций:
 * [[https://vk.com/video-38085148_456246867 Игоря Сергеевича ШИШКИНА]]
 ' [[https://vk.com/video-38085148_456246867 Чьими руками хотят снести власть в РФ. И. Шишкин]]
 ' Предыдущая лекция: [[https://vk.com/video-38085148_456246446 Запад хочет повторить в России Февраль 1917 года. И. Шишкин]]
 * [[https://vk.com/video-38085148_456245981 Александра Гельевича ДУГИНА]]
 ' [[https://vk.com/video-38085148_456245981 Глобалисты поспешили и поэтому проиграли. СВО как решающий момент глобальной битвы. А. Дугин]]
 * [[https://vk.com/video_ext.php?oid=-211000092&id=456239798&hash=0c25f465858dcd8e Константина Валентиновича СИВКОВА]]
 ' [[https://vk.com/video_ext.php?oid=-211000092&id=456239798&hash=0c25f465858dcd8e Курс геополитики (часть 5). Фундаментальная идеология. К. Сивков]]
 * [[https://vk.com/video-38085148_456246420 Константина Александровича Залесского]]
 ' [[https://vk.com/video-38085148_456246420 Возникновение фашизма в Европе. К. Залесский]]
 * [[https://vk.com/video-38085148_456247164 Александр Владимирович Гапоненко]]
 ' [[https://vk.com/video-38085148_456247164 Как XXI век стремительно возрождает коричневую чуму. А. Гапоненко]]
 * Андрея Ильича ФУРСОВА
 * [[https://nday.club/video/ispoved-ideologa Игоря СТЕЧКИНА (ONYQ)]]
 ' [[https://nday.club/video/ispoved-ideologa Джон Перкинс: «Исповедь экономического убийцы». И. Стечкин]]
Использованы информационные ресурсы:
 * [[https://dentv.ru/about/ Аналитический интернет-канал «День ТВ»]]
 * [[https://nday.club Телеканал «Новый День»]]
end legend

footer  <img:https://i.creativecommons.org/l/by-sa/4.0/88x31.png>

enum Фобии {
  Русофобия
  Славянофобия
  Антисемитизм
}

abstract Идеология{
..Определяет..
Цель социума
Средства достижения цели
}

class Колониализм{
}

class "Общество потребления"{
}

abstract Либерализм{
Изменения: Эволюционные
Личное/Общее: Абсолютно личное
Общество/Государство: Общество
Экономика: Свободный рынок
Гос власть: Разделение властей
Смена гос власти: Продажные выборы
Идеология: Тоталитарная, управляемая\n\t верхушкой элиты
Закон служит: Денежным мешкам
Выгодоприобретатель: Транснациональный капитал
}

abstract Марксизм{
Изменения: Революционные
Личное/Общее: Абсолютно общее
Общество/Государство: Государство
Экономика:Страна-корпорация
Гос власть: Единство ветвей власти
Смена гос власти: Формальные выборы
Идеология: Идеократия
Закон служит: Соц. справедливости
Выгодоприобретатель: Большинство

}

abstract Консерватизм{
Изменения: Тормозим
Личное/Общее: Общее
Общество/Государство: Государство
Экономика: Гос. регулирование
Гос власть: Разделение властей с ведущей
Смена гос власти: Формальные выборы
Идеология: Терпимость
Закон служит: Элите
Выгодоприобретатель: Элита
}

abstract Фашизм{
Изменения: Революционные
Личное/Общее: Абсолютно общее для господ. нации
Общество/Государство: Милитаризация всех сфер жизни
Экономика: Ведущая роль гос.
Гос власть: Организация по военному принципу
Смена гос власти: Узурпация
Идеология: Идеократия
Закон служит: Политической целесообразности
Выгодоприобретатель: Национальный капитал
}

abstract Нацизм {
как 2 стадия фашизма: переход от эксплуатации \nи дискриминации к физическому уничтожению
---
Личное/Общее: Абсолютно общее для господ. нации
Экономика: Ведущая роль гос.
Гос власть: Единство ветвей с приоритетом исполн.
Смена гос власти: Узурпация
Идеология: Идеократия
Закон служит: Политической целесообразности
Выгодоприобретатель: Национальный капитал
 Фобии[] 
}

abstract Анархизм{
Личное/Общее: Абсолютно личное
Экономика: Свободный рынок
Гос власть: Нет
Смена гос власти: —
Идеология: Плюрализм
Закон служит: Малым общинам
Выгодоприобретатель: Бандит
}

abstract "Компрадорский либерализм"{
Личное/Общее: Абсолютно личное
Экономика:Свободный рынок
Гос власть: Разделение властей
Смена гос власти: Продажные выборы
Идеология: Тоталитарная, управляемая\n\t верхушкой элиты
Закон служит: Денежным мешкам
Выгодоприобретатель: Метрополия
}

abstract "Авторитарный режим"{
Личное/Общее: Личное для элиты, общее для народа
Экономика: Гос. регулирование
Гос власть: Единство ветвей с приоритетом исполн.
Смена гос власти: Узурпация с формальными выборами
Идеология: Идеократия
Закон служит: Клан у власти
Выгодоприобретатель: Клан у власти
}

annotation  Русофобия #pink{
..Признаки:..
Гонения на Православную церковь
Взваливание на русских коллективной вины
Дискриминация по принадлежности к русскому народу
Противопоставление русских другим народам России,\n\t даже в позитивном ключе
Ненависть к русским, к русской культуре
Отношение к русским как к недочеловекам
Принадлежность к «малому народу» (по Шафаревичу)

}

annotation "Пятая колонна" #pink{
..Классификация..
1. Предатели купленные: единицы
2. Предатели «наивные» (наивно думают, что Запад — это почти рай): до 10%
3. Обманутый народ (когда поверит, что «заграница нам поможет»): до 70%
..Когда активно действовали..
Российская империя: 1917 год
СССР: 1980–1991 гг.
Украина: с 2013 года
Россия: 1991 — 24.02.2022
Россия после 24.02.2022 — пока не известно
..Ты узнаешь их по словам про..
Европу от Лиссабона до Владивостока
Деградировавшую элиту Запада
Необходимость прекратить войну
Нужно просить Запад научить нас как жить (отношения вассал — сюзерен)
Привлечение иностранных инвесторов
Ненужно производить то, что «плохо получается» — всё купим
.. Они продвигают..
Людей, искренни восхищающихся Западом
Кредитную зависимость от метрополии
Западные стандарты 
Общество потребления
Дибилизацию образования
.. Текущий (2023 год) статус пятой колонны в России..
Предатели купленные: есть, у них сейчас отбирают имущество
Предатели «наивные»: внедрены везде
Обманутый народ: нет
}

Идеология    <|--   Марксизм
Идеология    <|--   Консерватизм
Идеология    <|--   Либерализм
Идеология    <|--   Фашизм
Идеология    <|.right.  "Общество потребления" 
Идеология    <|.left.  "Колониализм"

Либерализм   <|--   Анархизм
Либерализм   <|--   "Компрадорский либерализм"

Консерватизм <|--   "Авторитарный режим"
Фашизм       <|--   Нацизм

Нацизм::Фобии *-down-"1..*" Фобии
Фобии::Русофобия *-left- Русофобия

@enduml